Started by user [8mha:////4KUMFlbveTuw2CrO3ffXNdXpt+NlAScdR1M+KzoPh3GjAAAAlx+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzWEgZu/dLi1CL9xJTczDwAj6GcLcAAAAA=[0madmin
Running as SYSTEM
Building in workspace /var/jenkins_home/jobs/diaspora_to_csv/workspace
[workspace] $ /bin/sh -xe /tmp/jenkins10308604077075839595.sh
+ pip install -r ./requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Collecting mysql_connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.9/11.9 MB 4.0 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: natsort==8.1.0 in /var/jenkins_home/.local/lib/python3.9/site-packages (from -r ./requirements.txt (line 3)) (8.1.0)
Requirement already satisfied: numpy==1.20.1 in /var/jenkins_home/.local/lib/python3.9/site-packages (from -r ./requirements.txt (line 4)) (1.20.1)
Requirement already satisfied: pandas==1.2.4 in /var/jenkins_home/.local/lib/python3.9/site-packages (from -r ./requirements.txt (line 5)) (1.2.4)
Requirement already satisfied: rdflib==6.1.1 in /var/jenkins_home/.local/lib/python3.9/site-packages (from -r ./requirements.txt (line 6)) (6.1.1)
Requirement already satisfied: requests==2.27.1 in /var/jenkins_home/.local/lib/python3.9/site-packages (from -r ./requirements.txt (line 7)) (2.27.1)
Requirement already satisfied: SPARQLWrapper==2.0.0 in /var/jenkins_home/.local/lib/python3.9/site-packages (from -r ./requirements.txt (line 8)) (2.0.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /var/jenkins_home/.local/lib/python3.9/site-packages (from pandas==1.2.4->-r ./requirements.txt (line 5)) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /var/jenkins_home/.local/lib/python3.9/site-packages (from pandas==1.2.4->-r ./requirements.txt (line 5)) (2022.1)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from rdflib==6.1.1->-r ./requirements.txt (line 6)) (52.0.0)
Requirement already satisfied: pyparsing in /var/jenkins_home/.local/lib/python3.9/site-packages (from rdflib==6.1.1->-r ./requirements.txt (line 6)) (3.0.9)
Requirement already satisfied: isodate in /var/jenkins_home/.local/lib/python3.9/site-packages (from rdflib==6.1.1->-r ./requirements.txt (line 6)) (0.6.1)
Requirement already satisfied: idna<4,>=2.5 in /var/jenkins_home/.local/lib/python3.9/site-packages (from requests==2.27.1->-r ./requirements.txt (line 7)) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /var/jenkins_home/.local/lib/python3.9/site-packages (from requests==2.27.1->-r ./requirements.txt (line 7)) (1.26.10)
Requirement already satisfied: charset-normalizer~=2.0.0 in /var/jenkins_home/.local/lib/python3.9/site-packages (from requests==2.27.1->-r ./requirements.txt (line 7)) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in /var/jenkins_home/.local/lib/python3.9/site-packages (from requests==2.27.1->-r ./requirements.txt (line 7)) (2022.6.15)
Requirement already satisfied: six>=1.5 in /var/jenkins_home/.local/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas==1.2.4->-r ./requirements.txt (line 5)) (1.16.0)
Building wheels for collected packages: mysql_connector
  Building wheel for mysql_connector (setup.py): started
  Building wheel for mysql_connector (setup.py): finished with status 'done'
  Created wheel for mysql_connector: filename=mysql_connector-2.2.9-cp39-cp39-linux_x86_64.whl size=247948 sha256=f8569031ba641f4d4213f59e0b78bfa684af31f42befeb1c87e22fd9e42f2c70
  Stored in directory: /var/jenkins_home/.cache/pip/wheels/7b/14/39/5aad423666e827dfe9a1fbcd111ac17171e7c9865d570780ce
Successfully built mysql_connector
Installing collected packages: mysql_connector
Successfully installed mysql_connector-2.2.9
+ python3 db_to_csv.py
/var/jenkins_home/jobs/diaspora_to_csv/workspace/db_to_csv.py:61: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
  config.readfp(open('./tables.properties'))
Traceback (most recent call last):
  File "/var/jenkins_home/.local/lib/python3.9/site-packages/mysql/connector/network.py", line 509, in open_connection
    self.sock.connect(sockaddr)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/jenkins_home/jobs/diaspora_to_csv/workspace/db_to_csv.py", line 74, in <module>
    mydb = mysql.connector.connect(
  File "/var/jenkins_home/.local/lib/python3.9/site-packages/mysql/connector/__init__.py", line 179, in connect
    return MySQLConnection(*args, **kwargs)
  File "/var/jenkins_home/.local/lib/python3.9/site-packages/mysql/connector/connection.py", line 95, in __init__
    self.connect(**kwargs)
  File "/var/jenkins_home/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 716, in connect
    self._open_connection()
  File "/var/jenkins_home/.local/lib/python3.9/site-packages/mysql/connector/connection.py", line 206, in _open_connection
    self._socket.open_connection()
  File "/var/jenkins_home/.local/lib/python3.9/site-packages/mysql/connector/network.py", line 511, in open_connection
    raise errors.InterfaceError(
mysql.connector.errors.InterfaceError: 2003: Can't connect to MySQL server on 'localhost:3306' (111 Connection refused)
Build step 'Execute shell' marked build as failure
Finished: FAILURE
